version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "eslint"
      update-types: ["version-update:semver-major"]
    - dependency-name: "eslint-config-prettier"
      update-types: ["version-update:semver-major"]
    - dependency-name: "lucide-react"
      update-types: ["version-update:semver-major"]
